// Generated by Dagger (https://google.github.io/dagger).
package com.wmt.hardip.ui.signup;

import androidx.fragment.app.Fragment;
import com.wmt.hardip.base.BaseActivity_MembersInjector;
import com.wmt.hardip.data.local.PreferencesHelper;
import com.wmt.hardip.di.util.ViewModelFactory;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import dagger.android.support.DaggerAppCompatActivity_MembersInjector;
import javax.inject.Provider;

public final class SignUPActivity_MembersInjector implements MembersInjector<SignUPActivity> {
  private final Provider<DispatchingAndroidInjector<Fragment>>
      dispatchingAndroidInjectorAndSupportFragmentInjectorProvider;

  private final Provider<DispatchingAndroidInjector<android.app.Fragment>>
      frameworkFragmentInjectorProvider;

  private final Provider<ViewModelFactory> viewModelFactoryProvider;

  private final Provider<PreferencesHelper> mPreferencesHelperProvider;

  public SignUPActivity_MembersInjector(
      Provider<DispatchingAndroidInjector<Fragment>>
          dispatchingAndroidInjectorAndSupportFragmentInjectorProvider,
      Provider<DispatchingAndroidInjector<android.app.Fragment>> frameworkFragmentInjectorProvider,
      Provider<ViewModelFactory> viewModelFactoryProvider,
      Provider<PreferencesHelper> mPreferencesHelperProvider) {
    this.dispatchingAndroidInjectorAndSupportFragmentInjectorProvider =
        dispatchingAndroidInjectorAndSupportFragmentInjectorProvider;
    this.frameworkFragmentInjectorProvider = frameworkFragmentInjectorProvider;
    this.viewModelFactoryProvider = viewModelFactoryProvider;
    this.mPreferencesHelperProvider = mPreferencesHelperProvider;
  }

  public static MembersInjector<SignUPActivity> create(
      Provider<DispatchingAndroidInjector<Fragment>>
          dispatchingAndroidInjectorAndSupportFragmentInjectorProvider,
      Provider<DispatchingAndroidInjector<android.app.Fragment>> frameworkFragmentInjectorProvider,
      Provider<ViewModelFactory> viewModelFactoryProvider,
      Provider<PreferencesHelper> mPreferencesHelperProvider) {
    return new SignUPActivity_MembersInjector(
        dispatchingAndroidInjectorAndSupportFragmentInjectorProvider,
        frameworkFragmentInjectorProvider,
        viewModelFactoryProvider,
        mPreferencesHelperProvider);
  }

  @Override
  public void injectMembers(SignUPActivity instance) {
    DaggerAppCompatActivity_MembersInjector.injectSupportFragmentInjector(
        instance, dispatchingAndroidInjectorAndSupportFragmentInjectorProvider.get());
    DaggerAppCompatActivity_MembersInjector.injectFrameworkFragmentInjector(
        instance, frameworkFragmentInjectorProvider.get());
    BaseActivity_MembersInjector.injectDispatchingAndroidInjector(
        instance, dispatchingAndroidInjectorAndSupportFragmentInjectorProvider.get());
    injectViewModelFactory(instance, viewModelFactoryProvider.get());
    injectMPreferencesHelper(instance, mPreferencesHelperProvider.get());
  }

  public static void injectViewModelFactory(
      SignUPActivity instance, ViewModelFactory viewModelFactory) {
    instance.viewModelFactory = viewModelFactory;
  }

  public static void injectMPreferencesHelper(
      SignUPActivity instance, PreferencesHelper mPreferencesHelper) {
    instance.mPreferencesHelper = mPreferencesHelper;
  }
}
