// Generated by Dagger (https://google.github.io/dagger).
package com.wmt.hardip.base;

import androidx.databinding.ViewDataBinding;
import androidx.fragment.app.Fragment;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import dagger.android.support.DaggerAppCompatActivity_MembersInjector;
import javax.inject.Provider;

public final class BaseActivity_MembersInjector<T extends ViewDataBinding, V extends BaseViewModel>
    implements MembersInjector<BaseActivity<T, V>> {
  private final Provider<DispatchingAndroidInjector<Fragment>>
      dispatchingAndroidInjectorAndSupportFragmentInjectorProvider;

  private final Provider<DispatchingAndroidInjector<android.app.Fragment>>
      frameworkFragmentInjectorProvider;

  public BaseActivity_MembersInjector(
      Provider<DispatchingAndroidInjector<Fragment>>
          dispatchingAndroidInjectorAndSupportFragmentInjectorProvider,
      Provider<DispatchingAndroidInjector<android.app.Fragment>>
          frameworkFragmentInjectorProvider) {
    this.dispatchingAndroidInjectorAndSupportFragmentInjectorProvider =
        dispatchingAndroidInjectorAndSupportFragmentInjectorProvider;
    this.frameworkFragmentInjectorProvider = frameworkFragmentInjectorProvider;
  }

  public static <T extends ViewDataBinding, V extends BaseViewModel>
      MembersInjector<BaseActivity<T, V>> create(
          Provider<DispatchingAndroidInjector<Fragment>>
              dispatchingAndroidInjectorAndSupportFragmentInjectorProvider,
          Provider<DispatchingAndroidInjector<android.app.Fragment>>
              frameworkFragmentInjectorProvider) {
    return new BaseActivity_MembersInjector<T, V>(
        dispatchingAndroidInjectorAndSupportFragmentInjectorProvider,
        frameworkFragmentInjectorProvider);
  }

  @Override
  public void injectMembers(BaseActivity<T, V> instance) {
    DaggerAppCompatActivity_MembersInjector.injectSupportFragmentInjector(
        instance, dispatchingAndroidInjectorAndSupportFragmentInjectorProvider.get());
    DaggerAppCompatActivity_MembersInjector.injectFrameworkFragmentInjector(
        instance, frameworkFragmentInjectorProvider.get());
    injectDispatchingAndroidInjector(
        instance, dispatchingAndroidInjectorAndSupportFragmentInjectorProvider.get());
  }

  public static <T extends ViewDataBinding, V extends BaseViewModel>
      void injectDispatchingAndroidInjector(
          BaseActivity<T, V> instance,
          DispatchingAndroidInjector<Fragment> dispatchingAndroidInjector) {
    instance.dispatchingAndroidInjector = dispatchingAndroidInjector;
  }
}
