// Generated by Dagger (https://google.github.io/dagger).
package com.wmt.hardip.data.rest;

import com.wmt.hardip.data.local.PreferencesHelper;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class ApiHeader_Factory implements Factory<ApiHeader> {
  private final Provider<PreferencesHelper> preferencesHelperProvider;

  public ApiHeader_Factory(Provider<PreferencesHelper> preferencesHelperProvider) {
    this.preferencesHelperProvider = preferencesHelperProvider;
  }

  @Override
  public ApiHeader get() {
    return new ApiHeader(preferencesHelperProvider.get());
  }

  public static ApiHeader_Factory create(Provider<PreferencesHelper> preferencesHelperProvider) {
    return new ApiHeader_Factory(preferencesHelperProvider);
  }

  public static ApiHeader newApiHeader(PreferencesHelper preferencesHelper) {
    return new ApiHeader(preferencesHelper);
  }
}
